[package]
name = "onchain-physics"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-vm = {git = "https://github.com/lambdaclass/cairo-rs.git", version = "0.1.1"}
cairo-felt = {git = "https://github.com/lambdaclass/cairo-rs.git", version = "0.1.0"}
num-bigint = "0.4"